// ============================================================
// PRODUCTS DATABASE - Shatakshi Surgicals
// ============================================================
const products = [
    // ==================== SURGICAL INSTRUMENTS ====================
    {
        id: 1,
        name: "Stainless Steel Surgical Scissor Set (5 Pcs)",
        category: "surgical-instruments",
        categoryName: "Surgical Instruments",
        brand: "Shatakshi",
        price: 1850,
        originalPrice: 2500,
        discount: 26,
        rating: 4.5,
        reviews: 128,
        image: "",
        icon: "fa-scissors",
        description: "Premium quality stainless steel surgical scissors set containing 5 different types - Mayo, Metzenbaum, Iris, Bandage, and Suture scissors. Made from high-grade German stainless steel for precision cutting and long-lasting sharpness.",
        features: ["German stainless steel", "5 types included", "Autoclavable", "Anti-rust coating", "Precision ground edges"],
        sku: "SS-SI-001",
        stock: 45,
        featured: true,
        tags: ["bestseller", "sale"]
    },
    {
        id: 2,
        name: "Surgical Forceps Set - Tissue & Dressing (8 Pcs)",
        category: "surgical-instruments",
        categoryName: "Surgical Instruments",
        brand: "Shatakshi",
        price: 2450,
        originalPrice: 3200,
        discount: 23,
        rating: 4.6,
        reviews: 94,
        image: "",
        icon: "fa-hand-holding-medical",
        description: "Complete surgical forceps set with 8 pieces including tissue forceps, dressing forceps, artery forceps, and sponge holders. Made from surgical-grade stainless steel with excellent grip.",
        features: ["8 piece complete set", "Surgical-grade steel", "Serrated tips", "Ratchet locking", "Autoclavable"],
        sku: "SS-SI-002",
        stock: 32,
        featured: true,
        tags: ["bestseller"]
    },
    {
        id: 3,
        name: "Needle Holder - Mayo Hegar 6 inch",
        category: "surgical-instruments",
        categoryName: "Surgical Instruments",
        brand: "Ethicon",
        price: 890,
        originalPrice: 1200,
        discount: 26,
        rating: 4.7,
        reviews: 156,
        image: "",
        icon: "fa-syringe",
        description: "Mayo Hegar needle holder, 6-inch length. Tungsten carbide insert jaws for superior needle grip. Ratchet lock mechanism for secure holding during suturing procedures.",
        features: ["Tungsten carbide jaws", "6-inch length", "Ratchet lock", "Cross-serrated jaws", "Ergonomic handle"],
        sku: "SS-SI-003",
        stock: 67,
        featured: true,
        tags: ["bestseller"]
    },
    {
        id: 4,
        name: "Scalpel Handle #3 with 10 Blades",
        category: "surgical-instruments",
        categoryName: "Surgical Instruments",
        brand: "B.Braun",
        price: 450,
        originalPrice: 600,
        discount: 25,
        rating: 4.4,
        reviews: 89,
        image: "",
        icon: "fa-cut",
        description: "Stainless steel scalpel handle #3 compatible with blades #10-15. Includes 10 sterile disposable carbon steel surgical blades. Perfect for precision incisions.",
        features: ["Handle #3 size", "10 blades included", "Sterile blades", "Carbon steel blades", "Non-slip grip"],
        sku: "SS-SI-004",
        stock: 120,
        featured: false,
        tags: ["sale"]
    },
    {
        id: 5,
        name: "Retractor Set - Army Navy & Langenbeck (4 Pcs)",
        category: "surgical-instruments",
        categoryName: "Surgical Instruments",
        brand: "Shatakshi",
        price: 1650,
        originalPrice: 2100,
        discount: 21,
        rating: 4.3,
        reviews: 47,
        image: "",
        icon: "fa-expand-arrows-alt",
        description: "Surgical retractor set containing 2 Army Navy retractors and 2 Langenbeck retractors. Essential for wound retraction during surgical procedures.",
        features: ["4 piece set", "Mirror polish finish", "Smooth edges", "Stainless steel", "Autoclavable"],
        sku: "SS-SI-005",
        stock: 28,
        featured: false,
        tags: []
    },
    {
        id: 6,
        name: "Suture Kit - Complete Practice Set",
        category: "surgical-instruments",
        categoryName: "Surgical Instruments",
        brand: "Ethicon",
        price: 1250,
        originalPrice: 1800,
        discount: 31,
        rating: 4.8,
        reviews: 213,
        image: "",
        icon: "fa-first-aid",
        description: "Complete suture practice kit with needle holder, forceps, scissors, silicone practice pad, and assorted suture threads. Ideal for medical students and training.",
        features: ["Complete kit", "Silicone pad included", "Multiple suture types", "Carry case", "Training manual"],
        sku: "SS-SI-006",
        stock: 55,
        featured: true,
        tags: ["bestseller", "sale"]
    },

    // ==================== DIAGNOSTIC EQUIPMENT ====================
    {
        id: 7,
        name: "Digital Blood Pressure Monitor - Arm Type",
        category: "diagnostic-equipment",
        categoryName: "Diagnostic Equipment",
        brand: "Omron",
        price: 1899,
        originalPrice: 2999,
        discount: 37,
        rating: 4.6,
        reviews: 342,
        image: "",
        icon: "fa-heartbeat",
        description: "Omron digital blood pressure monitor with IntelliSense technology. Features large LCD display, irregular heartbeat detection, and memory for 60 readings. FDA approved.",
        features: ["IntelliSense technology", "Large LCD display", "60 reading memory", "Irregular heartbeat detection", "FDA approved"],
        sku: "SS-DE-001",
        stock: 89,
        featured: true,
        tags: ["bestseller", "sale"]
    },
    {
        id: 8,
        name: "Pulse Oximeter - Fingertip SpO2 Monitor",
        category: "diagnostic-equipment",
        categoryName: "Diagnostic Equipment",
        brand: "Dr. Morepen",
        price: 799,
        originalPrice: 1500,
        discount: 47,
        rating: 4.4,
        reviews: 567,
        image: "",
        icon: "fa-hand-pointer",
        description: "Fingertip pulse oximeter for accurate SpO2 and pulse rate monitoring. OLED display with 4-direction rotation. Low power consumption with auto shut-off feature.",
        features: ["OLED display", "SpO2 & pulse rate", "Auto shut-off", "Low battery indicator", "Lanyard included"],
        sku: "SS-DE-002",
        stock: 200,
        featured: true,
        tags: ["bestseller", "sale"]
    },
    {
        id: 9,
        name: "Digital Infrared Thermometer - Non Contact",
        category: "diagnostic-equipment",
        categoryName: "Diagnostic Equipment",
        brand: "Dr. Morepen",
        price: 1299,
        originalPrice: 2200,
        discount: 41,
        rating: 4.3,
        reviews: 278,
        image: "",
        icon: "fa-thermometer-half",
        description: "Non-contact digital infrared thermometer with instant 1-second reading. Color-coded fever alarm, memory for 32 readings, and switchable °C/°F display.",
        features: ["1 second reading", "Non-contact", "Fever alarm", "32 reading memory", "°C/°F switchable"],
        sku: "SS-DE-003",
        stock: 150,
        featured: true,
        tags: ["sale"]
    },
    {
        id: 10,
        name: "Stethoscope - Dual Head Professional",
        category: "diagnostic-equipment",
        categoryName: "Diagnostic Equipment",
        brand: "3M",
        price: 3500,
        originalPrice: 4500,
        discount: 22,
        rating: 4.8,
        reviews: 189,
        image: "",
        icon: "fa-stethoscope",
        description: "3M Littmann Classic III stethoscope with dual-sided chestpiece. Tunable diaphragm technology, excellent acoustic performance. Ideal for general examination.",
        features: ["Tunable diaphragm", "Dual-sided chestpiece", "Soft-sealing ear tips", "5 year warranty", "Next-gen tubing"],
        sku: "SS-DE-004",
        stock: 43,
        featured: true,
        tags: ["bestseller"]
    },
    {
        id: 11,
        name: "Blood Glucose Monitor Kit with 50 Strips",
        category: "diagnostic-equipment",
        categoryName: "Diagnostic Equipment",
        brand: "Dr. Morepen",
        price: 1450,
        originalPrice: 2200,
        discount: 34,
        rating: 4.5,
        reviews: 412,
        image: "",
        icon: "fa-tint",
        description: "Complete blood glucose monitoring kit with glucometer, 50 test strips, lancets, lancing device, and carry case. Results in just 5 seconds with minimal blood sample.",
        features: ["5 second results", "50 strips included", "Tiny blood sample", "500 reading memory", "Carry case"],
        sku: "SS-DE-005",
        stock: 110,
        featured: false,
        tags: ["bestseller", "sale"]
    },
    {
        id: 12,
        name: "Diagnostic ENT Set - Otoscope & Ophthalmoscope",
        category: "diagnostic-equipment",
        categoryName: "Diagnostic Equipment",
        brand: "Shatakshi",
        price: 4200,
        originalPrice: 5800,
        discount: 28,
        rating: 4.4,
        reviews: 67,
        image: "",
        icon: "fa-eye",
        description: "Professional ENT diagnostic set with fiber optic otoscope and ophthalmoscope. LED illumination, multiple specula sizes, and rechargeable handle.",
        features: ["Fiber optic illumination", "LED light", "Rechargeable", "Multiple specula", "Carrying case"],
        sku: "SS-DE-006",
        stock: 22,
        featured: false,
        tags: []
    },

    // ==================== HOSPITAL FURNITURE ====================
    {
        id: 13,
        name: "Semi-Fowler Hospital Bed with Mattress",
        category: "hospital-furniture",
        categoryName: "Hospital Furniture",
        brand: "Shatakshi",
        price: 18500,
        originalPrice: 25000,
        discount: 26,
        rating: 4.3,
        reviews: 34,
        image: "",
        icon: "fa-bed",
        description: "Semi-Fowler hospital bed with collapsible side railings, adjustable head and foot sections, and 4-inch foam mattress. Castors with brakes for easy mobility.",
        features: ["Adjustable sections", "Side railings", "4\" foam mattress", "Castors with brakes", "IV pole holder"],
        sku: "SS-HF-001",
        stock: 8,
        featured: true,
        tags: ["bestseller"]
    },
    {
        id: 14,
        name: "Wheelchair - Folding Chrome Plated",
        category: "hospital-furniture",
        categoryName: "Hospital Furniture",
        brand: "Shatakshi",
        price: 6500,
        originalPrice: 8500,
        discount: 24,
        rating: 4.5,
        reviews: 89,
        image: "",
        icon: "fa-wheelchair",
        description: "Chrome-plated folding wheelchair with mag wheels, fixed armrest, and swing-away footrests. Weight capacity: 120 kg. Lightweight and easy to fold for transport.",
        features: ["Chrome plated frame", "Mag wheels", "120 kg capacity", "Folding design", "Swing-away footrests"],
        sku: "SS-HF-002",
        stock: 15,
        featured: false,
        tags: ["sale"]
    },
    {
        id: 15,
        name: "Examination Table - Adjustable with Storage",
        category: "hospital-furniture",
        categoryName: "Hospital Furniture",
        brand: "Shatakshi",
        price: 12500,
        originalPrice: 16000,
        discount: 22,
        rating: 4.2,
        reviews: 28,
        image: "",
        icon: "fa-procedures",
        description: "Medical examination table with adjustable backrest, padded cushion, and under-shelf storage. Stainless steel frame with powder-coated finish.",
        features: ["Adjustable backrest", "Padded cushion", "Under-shelf storage", "SS frame", "Easy to clean"],
        sku: "SS-HF-003",
        stock: 6,
        featured: false,
        tags: []
    },
    {
        id: 16,
        name: "IV Stand - Stainless Steel 5 Legs",
        category: "hospital-furniture",
        categoryName: "Hospital Furniture",
        brand: "Shatakshi",
        price: 1800,
        originalPrice: 2400,
        discount: 25,
        rating: 4.4,
        reviews: 56,
        image: "",
        icon: "fa-prescription-bottle-alt",
        description: "Stainless steel IV stand with 5 legs and 4 hooks. Height adjustable from 135cm to 220cm. Stable base with smooth-rolling castors.",
        features: ["5 leg base", "4 hooks", "Height adjustable", "Smooth castors", "Stainless steel"],
        sku: "SS-HF-004",
        stock: 30,
        featured: false,
        tags: []
    },

    // ==================== OT EQUIPMENT ====================
    {
        id: 17,
        name: "Electrosurgical Cautery Unit - 300W",
        category: "ot-equipment",
        categoryName: "OT Equipment",
        brand: "Shatakshi",
        price: 45000,
        originalPrice: 58000,
        discount: 22,
        rating: 4.6,
        reviews: 23,
        image: "",
        icon: "fa-bolt",
        description: "300W electrosurgical cautery unit with monopolar and bipolar modes. Digital display, multiple cutting and coagulation modes. Complete with patient plate and accessories.",
        features: ["300W power", "Monopolar & Bipolar", "Digital display", "Multiple modes", "Safety features"],
        sku: "SS-OT-001",
        stock: 5,
        featured: true,
        tags: []
    },
    {
        id: 18,
        name: "Suction Machine - Portable Electric",
        category: "ot-equipment",
        categoryName: "OT Equipment",
        brand: "Shatakshi",
        price: 8500,
        originalPrice: 12000,
        discount: 29,
        rating: 4.5,
        reviews: 45,
        image: "",
        icon: "fa-wind",
        description: "Portable electric suction machine with 1-liter collection jar. Adjustable suction pressure, overflow protection, and low noise operation. Ideal for clinics and home care.",
        features: ["1L collection jar", "Adjustable pressure", "Overflow protection", "Low noise", "Portable design"],
        sku: "SS-OT-002",
        stock: 18,
        featured: false,
        tags: ["sale"]
    },
    {
        id: 19,
        name: "Autoclave Machine - 22 Liter Table Top",
        category: "ot-equipment",
        categoryName: "OT Equipment",
        brand: "Shatakshi",
        price: 15500,
        originalPrice: 20000,
        discount: 23,
        rating: 4.7,
        reviews: 67,
        image: "",
        icon: "fa-shield-virus",
        description: "22-liter table-top autoclave sterilizer with digital display and auto shut-off. Achieves 121°C at 15 PSI for complete sterilization. Stainless steel drum with 3 trays.",
        features: ["22L capacity", "Digital display", "Auto shut-off", "3 SS trays", "Safety valve"],
        sku: "SS-OT-003",
        stock: 12,
        featured: true,
        tags: ["bestseller"]
    },
    {
        id: 20,
        name: "OT Light - Ceiling Mounted LED Shadowless",
        category: "ot-equipment",
        categoryName: "OT Equipment",
        brand: "Philips",
        price: 85000,
        originalPrice: 110000,
        discount: 23,
        rating: 4.8,
        reviews: 15,
        image: "",
        icon: "fa-lightbulb",
        description: "Ceiling-mounted LED surgical OT light with shadowless illumination. 160,000 lux intensity, color temperature adjustment, and flexible positioning arm.",
        features: ["160,000 lux", "LED technology", "Shadowless", "Color temp adjust", "Flexible arm"],
        sku: "SS-OT-004",
        stock: 3,
        featured: false,
        tags: []
    },

    // ==================== DISPOSABLES & CONSUMABLES ====================
    {
        id: 21,
        name: "Surgical Gloves - Sterile Latex (Box of 50 pairs)",
        category: "disposables",
        categoryName: "Disposables & Consumables",
        brand: "Hindustan Syringes",
        price: 650,
        originalPrice: 900,
        discount: 28,
        rating: 4.3,
        reviews: 567,
        image: "",
        icon: "fa-hand-sparkles",
        description: "Pre-powdered sterile latex surgical gloves, box of 50 pairs. Available in sizes 6.0 to 8.5. Excellent tactile sensitivity and barrier protection.",
        features: ["50 pairs/box", "Sterile", "Pre-powdered", "Multiple sizes", "Latex material"],
        sku: "SS-DC-001",
        stock: 300,
        featured: true,
        tags: ["bestseller"]
    },
    {
        id: 22,
        name: "Disposable Syringes 5ml with Needle (Box of 100)",
        category: "disposables",
        categoryName: "Disposables & Consumables",
        brand: "Hindustan Syringes",
        price: 350,
        originalPrice: 500,
        discount: 30,
        rating: 4.5,
        reviews: 890,
        image: "",
        icon: "fa-syringe",
        description: "Dispovan disposable syringes 5ml with 24G needle attached. Luer mount, clear barrel with easy-to-read graduations. EO sterilized, individually packed.",
        features: ["100 pcs/box", "5ml capacity", "24G needle", "EO sterilized", "Individually packed"],
        sku: "SS-DC-002",
        stock: 500,
        featured: false,
        tags: ["bestseller"]
    },
    {
        id: 23,
        name: "3-Ply Surgical Face Masks (Box of 100)",
        category: "disposables",
        categoryName: "Disposables & Consumables",
        brand: "3M",
        price: 280,
        originalPrice: 450,
        discount: 38,
        rating: 4.2,
        reviews: 1245,
        image: "",
        icon: "fa-head-side-mask",
        description: "3-ply surgical face masks with nose wire and ear loops. BFE > 95%, splash resistant. Comfortable fit with adjustable nose clip. Box of 100 masks.",
        features: ["100 masks/box", "3-ply protection", "BFE > 95%", "Nose wire", "Ear loops"],
        sku: "SS-DC-003",
        stock: 800,
        featured: false,
        tags: ["sale"]
    },
    {
        id: 24,
        name: "Surgical Sutures - Absorbable Catgut (12 pcs)",
        category: "disposables",
        categoryName: "Disposables & Consumables",
        brand: "Ethicon",
        price: 1200,
        originalPrice: 1600,
        discount: 25,
        rating: 4.6,
        reviews: 156,
        image: "",
        icon: "fa-band-aid",
        description: "Chromic catgut absorbable sutures, 12 pieces per box. Available in sizes 2-0 to 4-0 with various needle types. Ethicon quality for reliable wound closure.",
        features: ["12 pcs/box", "Absorbable", "Chromic catgut", "Multiple sizes", "Sterile packed"],
        sku: "SS-DC-004",
        stock: 75,
        featured: false,
        tags: []
    },
    {
        id: 25,
        name: "IV Cannula Set - Assorted Sizes (Box of 50)",
        category: "disposables",
        categoryName: "Disposables & Consumables",
        brand: "B.Braun",
        price: 750,
        originalPrice: 1000,
        discount: 25,
        rating: 4.4,
        reviews: 234,
        image: "",
        icon: "fa-prescription-bottle",
        description: "B.Braun IV cannula set with assorted sizes (18G, 20G, 22G, 24G). Safety mechanism, smooth insertion, and secure fixation wings. EO sterilized.",
        features: ["50 pcs/box", "Assorted sizes", "Safety mechanism", "Wings for fixation", "EO sterilized"],
        sku: "SS-DC-005",
        stock: 200,
        featured: false,
        tags: []
    },
    {
        id: 26,
        name: "Cotton Roll - Absorbent (500g pack)",
        category: "disposables",
        categoryName: "Disposables & Consumables",
        brand: "Shatakshi",
        price: 180,
        originalPrice: 250,
        discount: 28,
        rating: 4.1,
        reviews: 345,
        image: "",
        icon: "fa-cloud",
        description: "Premium quality absorbent cotton roll, 500g pack. Highly absorbent, soft, and clean. Suitable for wound dressing, cleaning, and general medical use.",
        features: ["500g pack", "Highly absorbent", "Soft & clean", "Medical grade", "BP standard"],
        sku: "SS-DC-006",
        stock: 400,
        featured: false,
        tags: []
    },

    // ==================== ORTHOPAEDIC SUPPLIES ====================
    {
        id: 27,
        name: "Knee Support - Hinged Neoprene Brace",
        category: "orthopaedic",
        categoryName: "Orthopaedic Supplies",
        brand: "Shatakshi",
        price: 1200,
        originalPrice: 1800,
        discount: 33,
        rating: 4.4,
        reviews: 189,
        image: "",
        icon: "fa-bone",
        description: "Hinged neoprene knee support brace with adjustable straps. Provides excellent lateral support and compression. Available in S, M, L, XL sizes.",
        features: ["Hinged design", "Neoprene material", "Adjustable straps", "Multiple sizes", "Breathable"],
        sku: "SS-OR-001",
        stock: 60,
        featured: false,
        tags: ["sale"]
    },
    {
        id: 28,
        name: "Cervical Collar - Soft with Support",
        category: "orthopaedic",
        categoryName: "Orthopaedic Supplies",
        brand: "Shatakshi",
        price: 450,
        originalPrice: 650,
        discount: 31,
        rating: 4.3,
        reviews: 134,
        image: "",
        icon: "fa-head-side-virus",
        description: "Soft cervical collar with chin support for neck pain relief and post-injury support. Anatomical design with cotton stockinette cover. Adjustable with velcro closure.",
        features: ["Soft support", "Chin support", "Cotton cover", "Velcro closure", "Adjustable height"],
        sku: "SS-OR-002",
        stock: 45,
        featured: false,
        tags: []
    },
    {
        id: 29,
        name: "Walking Stick - Adjustable Aluminium",
        category: "orthopaedic",
        categoryName: "Orthopaedic Supplies",
        brand: "Shatakshi",
        price: 550,
        originalPrice: 800,
        discount: 31,
        rating: 4.5,
        reviews: 78,
        image: "",
        icon: "fa-cane",
        description: "Lightweight aluminium walking stick with height adjustment. Ergonomic handle with rubber grip. Anti-slip rubber tip for secure footing. Weight capacity: 100 kg.",
        features: ["Height adjustable", "Aluminium body", "Rubber grip", "Anti-slip tip", "100 kg capacity"],
        sku: "SS-OR-003",
        stock: 35,
        featured: false,
        tags: []
    },
    {
        id: 30,
        name: "Elastic Crepe Bandage (Pack of 12)",
        category: "orthopaedic",
        categoryName: "Orthopaedic Supplies",
        brand: "Shatakshi",
        price: 480,
        originalPrice: 700,
        discount: 31,
        rating: 4.2,
        reviews: 256,
        image: "",
        icon: "fa-bandage",
        description: "Elastic crepe bandage pack of 12 rolls, 4 inch width x 4 meters stretched length. Ideal for sprains, strains, and compression therapy. Washable and reusable.",
        features: ["12 rolls/pack", "4 inch width", "4m stretched", "Washable", "Reusable"],
        sku: "SS-OR-004",
        stock: 150,
        featured: false,
        tags: []
    },

    // ==================== PHARMACEUTICALS ====================
    {
        id: 31,
        name: "Povidone Iodine Solution 5% - 500ml",
        category: "pharmaceuticals",
        categoryName: "Pharmaceuticals",
        brand: "Shatakshi",
        price: 180,
        originalPrice: 250,
        discount: 28,
        rating: 4.5,
        reviews: 567,
        image: "",
        icon: "fa-flask",
        description: "Povidone Iodine (Betadine) antiseptic solution 5%, 500ml bottle. Broad-spectrum antimicrobial for skin disinfection, wound cleaning, and surgical site preparation.",
        features: ["500ml bottle", "5% concentration", "Broad spectrum", "Antiseptic", "For external use"],
        sku: "SS-PH-001",
        stock: 250,
        featured: false,
        tags: ["bestseller"]
    },
    {
        id: 32,
        name: "Hand Sanitizer - 70% Alcohol (500ml)",
        category: "pharmaceuticals",
        categoryName: "Pharmaceuticals",
        brand: "3M",
        price: 220,
        originalPrice: 350,
        discount: 37,
        rating: 4.3,
        reviews: 890,
        image: "",
        icon: "fa-pump-soap",
        description: "Hospital-grade hand sanitizer with 70% isopropyl alcohol. Kills 99.9% of germs. Quick-drying, non-sticky formula with moisturizing agents.",
        features: ["500ml bottle", "70% alcohol", "Quick drying", "Moisturizing", "Kills 99.9% germs"],
        sku: "SS-PH-002",
        stock: 300,
        featured: false,
        tags: ["sale"]
    },
    {
        id: 33,
        name: "Hydrogen Peroxide Solution 3% - 1 Liter",
        category: "pharmaceuticals",
        categoryName: "Pharmaceuticals",
        brand: "Shatakshi",
        price: 120,
        originalPrice: 180,
        discount: 33,
        rating: 4.2,
        reviews: 345,
        image: "",
        icon: "fa-prescription-bottle-alt",
        description: "Hydrogen peroxide solution 3% (10 volumes), 1-liter bottle. Used for wound cleaning, oral rinse, and surface disinfection. Pharmaceutical grade.",
        features: ["1 liter bottle", "3% concentration", "Pharmaceutical grade", "Multi-purpose", "Wound cleaning"],
        sku: "SS-PH-003",
        stock: 180,
        featured: false,
        tags: []
    },
    {
        id: 34,
        name: "First Aid Kit - Complete 120 Piece Professional",
        category: "pharmaceuticals",
        categoryName: "Pharmaceuticals",
        brand: "Shatakshi",
        price: 1500,
        originalPrice: 2200,
        discount: 32,
        rating: 4.6,
        reviews: 234,
        image: "",
        icon: "fa-briefcase-medical",
        description: "Professional 120-piece first aid kit in a durable hard case. Includes bandages, antiseptics, scissors, tweezers, gloves, gauze, and more. Ideal for clinics, offices, and homes.",
        features: ["120 pieces", "Hard case", "Complete kit", "Portable", "Wall mountable"],
        sku: "SS-PH-004",
        stock: 70,
        featured: true,
        tags: ["bestseller", "sale"]
    },
    {
        id: 35,
        name: "Surgical Spirit - 400ml",
        category: "pharmaceuticals",
        categoryName: "Pharmaceuticals",
        brand: "Shatakshi",
        price: 95,
        originalPrice: 140,
        discount: 32,
        rating: 4.1,
        reviews: 189,
        image: "",
        icon: "fa-bottle-droplet",
        description: "Surgical spirit (methylated spirit) 400ml bottle. Used for skin preparation before injection and minor surgical procedures. Also used for cleaning medical instruments.",
        features: ["400ml bottle", "Skin preparation", "Quick evaporation", "Medical grade", "Multipurpose"],
        sku: "SS-PH-005",
        stock: 220,
        featured: false,
        tags: []
    },
    {
        id: 36,
        name: "Nebulizer Machine - Compressor Type",
        category: "diagnostic-equipment",
        categoryName: "Diagnostic Equipment",
        brand: "Omron",
        price: 2200,
        originalPrice: 3500,
        discount: 37,
        rating: 4.5,
        reviews: 312,
        image: "",
        icon: "fa-lungs",
        description: "Omron compressor nebulizer machine for respiratory treatment. Efficient medication delivery, low noise operation, and easy-to-clean components. Includes adult and child masks.",
        features: ["Compressor type", "Low noise", "2 masks included", "Easy to clean", "Efficient delivery"],
        sku: "SS-DE-007",
        stock: 55,
        featured: true,
        tags: ["bestseller", "sale"]
    }
];
